/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
    PrismaClientKnownRequestError,
    PrismaClientUnknownRequestError,
    PrismaClientRustPanicError,
    PrismaClientInitializationError,
    PrismaClientValidationError,
    getPrismaClient,
    sqltag,
    empty,
    join,
    raw,
    skip,
    Decimal,
    Debug,
    DbNull,
    JsonNull,
    AnyNull,
    NullTypes,
    makeStrictEnum,
    Extensions,
    warnOnce,
    defineDmmfProperty,
    Public,
    getRuntime,
    createParam,
} = require("./runtime/client.js");

const Prisma = {};

exports.Prisma = Prisma;
exports.$Enums = {};

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
    client: "7.3.0",
    engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735",
};

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError;
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError;
Prisma.PrismaClientInitializationError = PrismaClientInitializationError;
Prisma.PrismaClientValidationError = PrismaClientValidationError;
Prisma.Decimal = Decimal;

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag;
Prisma.empty = empty;
Prisma.join = join;
Prisma.raw = raw;
Prisma.validator = Public.validator;

/**
 * Extensions
 */
Prisma.getExtensionContext = Extensions.getExtensionContext;
Prisma.defineExtension = Extensions.defineExtension;

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull;
Prisma.JsonNull = JsonNull;
Prisma.AnyNull = AnyNull;

Prisma.NullTypes = NullTypes;

const path = require("path");

/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
    ReadUncommitted: "ReadUncommitted",
    ReadCommitted: "ReadCommitted",
    RepeatableRead: "RepeatableRead",
    Serializable: "Serializable",
});

exports.Prisma.UserScalarFieldEnum = {
    id: "id",
    name: "name",
    email: "email",
    emailVerified: "emailVerified",
    image: "image",
    isAdmin: "isAdmin",
    isBlocked: "isBlocked",
    createdAt: "createdAt",
    updatedAt: "updatedAt",
};

exports.Prisma.PostScalarFieldEnum = {
    id: "id",
    userId: "userId",
    title: "title",
    content: "content",
    published: "published",
    authorId: "authorId",
    createdAt: "createdAt",
    updatedAt: "updatedAt",
};

exports.Prisma.SessionScalarFieldEnum = {
    session_token: "session_token",
    userId: "userId",
    expires: "expires",
    createdAt: "createdAt",
    updatedAt: "updatedAt",
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
    identifier: "identifier",
    token: "token",
    expires: "expires",
};

exports.Prisma.SortOrder = {
    asc: "asc",
    desc: "desc",
};

exports.Prisma.QueryMode = {
    default: "default",
    insensitive: "insensitive",
};

exports.Prisma.NullsOrder = {
    first: "first",
    last: "last",
};

exports.Prisma.ModelName = {
    User: "User",
    Post: "Post",
    Session: "Session",
    VerificationToken: "VerificationToken",
};
/**
 * Create the Client
 */
const config = {
    previewFeatures: ["postgresqlExtensions"],
    clientVersion: "7.3.0",
    engineVersion: "9d6ad21cbbceab97458517b147a6a09ff43aa735",
    activeProvider: "postgresql",
    inlineSchema:
        'generator client {\n  provider        = "prisma-client-js"\n  output          = "./prisma-client"\n  binaryTargets   = ["native", "darwin", "rhel-openssl-3.0.x"]\n  previewFeatures = ["postgresqlExtensions"]\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id            String    @id @default(cuid())\n  name          String?\n  email         String    @unique\n  emailVerified DateTime?\n  image         String?\n  isAdmin       Boolean   @default(false)\n  isBlocked     Boolean   @default(false)\n  createdAt     DateTime  @default(now())\n  updatedAt     DateTime  @updatedAt\n  posts         Post[]\n  sessions      Session[]\n}\n\nmodel Post {\n  id        Int      @id @default(autoincrement())\n  userId    String\n  title     String\n  content   String\n  published Boolean  @default(false)\n  authorId  Int?\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n}\n\nmodel Session {\n  session_token String   @unique\n  userId        String\n  expires       DateTime\n  createdAt     DateTime @default(now())\n  updatedAt     DateTime @updatedAt\n  user          User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n}\n\nmodel VerificationToken {\n  identifier String\n  token      String\n  expires    DateTime\n\n  @@id([identifier, token])\n}\n',
};

config.runtimeDataModel = JSON.parse(
    '{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"DateTime"},{"name":"image","kind":"scalar","type":"String"},{"name":"isAdmin","kind":"scalar","type":"Boolean"},{"name":"isBlocked","kind":"scalar","type":"Boolean"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"posts","kind":"object","type":"Post","relationName":"PostToUser"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"}],"dbName":null},"Post":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"userId","kind":"scalar","type":"String"},{"name":"title","kind":"scalar","type":"String"},{"name":"content","kind":"scalar","type":"String"},{"name":"published","kind":"scalar","type":"Boolean"},{"name":"authorId","kind":"scalar","type":"Int"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"PostToUser"}],"dbName":null},"Session":{"fields":[{"name":"session_token","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"expires","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":null},"VerificationToken":{"fields":[{"name":"identifier","kind":"scalar","type":"String"},{"name":"token","kind":"scalar","type":"String"},{"name":"expires","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}',
);
defineDmmfProperty(exports.Prisma, config.runtimeDataModel);
config.compilerWasm = {
    getRuntime: async () => require("./query_compiler_fast_bg.js"),
    getQueryCompilerWasmModule: async () => {
        const { Buffer } = require("node:buffer");
        const { wasm } = require("./query_compiler_fast_bg.wasm-base64.js");
        const queryCompilerWasmFileBytes = Buffer.from(wasm, "base64");

        return new WebAssembly.Module(queryCompilerWasmFileBytes);
    },
    importName: "./query_compiler_fast_bg.js",
};

const PrismaClient = getPrismaClient(config);
exports.PrismaClient = PrismaClient;
Object.assign(exports, Prisma);
