import "../design/input.css";
import { ThemeProvider } from "@/components/ui/theme/ThemeProvider";
import { cn } from "@/lib/utils";
import { robotoRegular } from "@/design/fontDefaults";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={cn(robotoRegular.className)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
